/* GENERATED by scripts/extract-icons.mjs — do not edit by hand.
 * Source of truth is the .svg files beside this one; rerun the script after
 * changing them. 44 icons, lifted out of the inline sprites that the
 * old pages each carried a copy of.
 */

export type IconId =
  | 'i-area'
  | 'i-arrow'
  | 'i-article'
  | 'i-bin'
  | 'i-binocs'
  | 'i-bird'
  | 'i-board'
  | 'i-boat'
  | 'i-book'
  | 'i-brick'
  | 'i-building'
  | 'i-bulb'
  | 'i-cap'
  | 'i-clipboard'
  | 'i-coins'
  | 'i-heart'
  | 'i-helmet'
  | 'i-laptop'
  | 'i-mangrove'
  | 'i-map'
  | 'i-megaphone'
  | 'i-nest'
  | 'i-paw'
  | 'i-people'
  | 'i-post'
  | 'i-recycle'
  | 'i-route'
  | 'i-ruler'
  | 'i-scroll'
  | 'i-seagrass'
  | 'i-shield'
  | 'i-station'
  | 'i-tree'
  | 'p-bandana'
  | 'p-book'
  | 'p-cap'
  | 'p-note'
  | 'p-pin'
  | 'p-poster'
  | 'p-print'
  | 'p-shirt'
  | 'p-sticker'
  | 'p-tote'
  | 'p-tumbler';

export const ICONS: Record<IconId, { viewBox: string; body: string }> = {
  'i-area': { viewBox: '0 0 24 24', body: "<rect x=\"3.5\" y=\"3.5\" width=\"7\" height=\"7\" rx=\"1\"/><rect x=\"13.5\" y=\"3.5\" width=\"7\" height=\"7\" rx=\"1\"/><rect x=\"3.5\" y=\"13.5\" width=\"7\" height=\"7\" rx=\"1\"/><path d=\"M13.5 17.2h7M17 13.7v7\"/>" },
  'i-arrow': { viewBox: '0 0 32 32', body: "<path d=\"M5 5 L26 26 M26 11 L26 26 L11 26\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"4\" stroke-linecap=\"square\" stroke-linejoin=\"miter\"/>" },
  'i-article': { viewBox: '0 0 24 24', body: "<rect x=\"4.5\" y=\"3.5\" width=\"15\" height=\"17\" rx=\"2\"/><path d=\"M8 8h8M8 12h8M8 16h5\"/>" },
  'i-bin': { viewBox: '0 0 24 24', body: "<path d=\"M4.5 7h15\"/><path d=\"M9 7V4.9a1.3 1.3 0 0 1 1.3-1.4h3.4A1.3 1.3 0 0 1 15 4.9V7\"/><path d=\"M6.6 7l.9 12a1.8 1.8 0 0 0 1.8 1.7h5.4a1.8 1.8 0 0 0 1.8-1.7l.9-12\"/><path d=\"M10 11v6M14 11v6\"/>" },
  'i-binocs': { viewBox: '0 0 24 24', body: "<rect x=\"3.5\" y=\"8\" width=\"6\" height=\"11\" rx=\"3\"/><rect x=\"14.5\" y=\"8\" width=\"6\" height=\"11\" rx=\"3\"/><path d=\"M9.5 12.5h5\"/><path d=\"M6.5 8V6.2a1.5 1.5 0 0 1 3 0V8M14.5 8V6.2a1.5 1.5 0 0 1 3 0V8\"/>" },
  'i-bird': { viewBox: '0 0 24 24', body: "<path d=\"M2 13c1.6-3 3.4-4.5 5.4-4.5 2 0 3.6 1.5 4.6 4.5\"/><path d=\"M12 13c1-3 2.6-4.5 4.6-4.5 2 0 3.8 1.5 5.4 4.5\"/>" },
  'i-board': { viewBox: '0 0 24 24', body: "<rect x=\"3.5\" y=\"4\" width=\"17\" height=\"11.5\" rx=\"1.6\"/><path d=\"M12 15.5V20\"/><path d=\"M8.5 20h7\"/><path d=\"M7.5 12l2.5-3 2.5 2.2 3-3.7\"/>" },
  'i-boat': { viewBox: '0 0 24 24', body: "<path d=\"M3.5 15h17l-2.5 4.3a2 2 0 0 1-1.7 1H7.7a2 2 0 0 1-1.7-1L3.5 15Z\"/><path d=\"M12 15V4l6.5 8.6H12\"/><path d=\"M12 15H6.5L12 9.2\"/>" },
  'i-book': { viewBox: '0 0 24 24', body: "<path d=\"M5 4h11a2 2 0 0 1 2 2v13H7a2 2 0 0 0-2 2V4Z\"/><path d=\"M5 19a2 2 0 0 1 2-2h11\"/>" },
  'i-brick': { viewBox: '0 0 24 24', body: "<rect x=\"3\" y=\"7\" width=\"18\" height=\"10\" rx=\"1.4\"/><path d=\"M3 12h18M9.5 7v5M15 12v5\"/>" },
  'i-building': { viewBox: '0 0 24 24', body: "<path d=\"M4.5 20.5V6.2L12 3.5l7.5 2.7v14.3\"/><path d=\"M2.5 20.5h19\"/><path d=\"M9.2 20.5v-4.2h5.6v4.2\"/><path d=\"M8.5 9.6h2M13.5 9.6h2M8.5 13.2h2M13.5 13.2h2\"/>" },
  'i-bulb': { viewBox: '0 0 24 24', body: "<path d=\"M9.2 16.4a6 6 0 1 1 5.6 0\"/><path d=\"M9.5 16.4h5v2.1a2.5 2.5 0 0 1-5 0v-2.1Z\"/><path d=\"M11 21h2\"/>" },
  'i-cap': { viewBox: '0 0 24 24', body: "<path d=\"M12 4 2.5 8.2 12 12.4l9.5-4.2L12 4Z\"/><path d=\"M6 10.4v4.3c0 1.9 2.7 3.3 6 3.3s6-1.4 6-3.3v-4.3\"/>" },
  'i-clipboard': { viewBox: '0 0 24 24', body: "<rect x=\"5\" y=\"4.5\" width=\"14\" height=\"16\" rx=\"2\"/><path d=\"M9 4.5V3.4h6v1.1\"/><path d=\"M9 10h6M9 13.6h6M9 17.2h3.6\"/>" },
  'i-coins': { viewBox: '0 0 24 24', body: "<ellipse cx=\"12\" cy=\"6.5\" rx=\"7\" ry=\"3\"/><path d=\"M5 6.5v4c0 1.7 3.1 3 7 3s7-1.3 7-3v-4\"/><path d=\"M5 10.5v4c0 1.7 3.1 3 7 3s7-1.3 7-3v-4\"/>" },
  'i-heart': { viewBox: '0 0 24 24', body: "<path d=\"M12 20.4S3.6 15 3.6 9.5A4.9 4.9 0 0 1 12 6.3a4.9 4.9 0 0 1 8.4 3.2c0 5.5-8.4 10.9-8.4 10.9Z\"/>" },
  'i-helmet': { viewBox: '0 0 24 24', body: "<path d=\"M3.5 17.5h17\"/><path d=\"M5.5 17.5v-2.2a6.5 6.5 0 0 1 13 0v2.2\"/><path d=\"M10.2 4.9a6.6 6.6 0 0 0-1.4 6\"/>" },
  'i-laptop': { viewBox: '0 0 24 24', body: "<rect x=\"5\" y=\"5\" width=\"14\" height=\"9.5\" rx=\"1.6\"/><path d=\"M2.5 18h19\"/><path d=\"M9.4 18l.6-1.6h4l.6 1.6\"/><path d=\"M10.2 9.4l1.6 1.6-1.6 1.6M13.8 9.4v3.2\"/>" },
  'i-mangrove': { viewBox: '0 0 24 24', body: "<circle cx=\"12\" cy=\"8.6\" r=\"4.6\"/><path d=\"M12 13.2V21\"/><path d=\"M8 21c0-2.6 1.7-3.6 4-5.6M16 21c0-2.6-1.7-3.6-4-5.6\"/>" },
  'i-map': { viewBox: '0 0 24 24', body: "<path d=\"M9 4 3 6.2v14L9 18l6 2.2 6-2.2v-14L15 6.2 9 4Z\"/><path d=\"M9 4v14M15 6.2v14\"/>" },
  'i-megaphone': { viewBox: '0 0 24 24', body: "<path d=\"M4 10.5v3A1.5 1.5 0 0 0 5.5 15h1.8l7.7 4V5l-7.7 4H5.5A1.5 1.5 0 0 0 4 10.5Z\"/><path d=\"M18 9.2a4 4 0 0 1 0 5.6\"/><path d=\"M7.3 15v3.4a1.5 1.5 0 0 0 3 0V16\"/>" },
  'i-nest': { viewBox: '0 0 24 24', body: "<path d=\"M3.5 14.8c0 3.5 3.8 5.4 8.5 5.4s8.5-1.9 8.5-5.4c0-1.6-2-2.4-4-2.4H7.5c-2 0-4 .8-4 2.4Z\"/><circle cx=\"9.6\" cy=\"11\" r=\"2\"/><circle cx=\"14.4\" cy=\"11\" r=\"2\"/>" },
  'i-paw': { viewBox: '0 0 24 24', body: "<circle cx=\"6.8\" cy=\"10.2\" r=\"2\"/><circle cx=\"12\" cy=\"7.6\" r=\"2\"/><circle cx=\"17.2\" cy=\"10.2\" r=\"2\"/><path d=\"M12 12.6c3 0 5 1.9 5 4.1s-2.2 3-5 3-5-.8-5-3 2-4.1 5-4.1Z\"/>" },
  'i-people': { viewBox: '0 0 24 24', body: "<circle cx=\"9\" cy=\"8\" r=\"3.2\"/><path d=\"M3 20c0-3.3 2.7-5.2 6-5.2s6 1.9 6 5.2\"/><path d=\"M16 5.6a3.2 3.2 0 0 1 0 6.4\"/><path d=\"M17.5 14.4c2.2.6 3.5 2.2 3.5 4.6\"/>" },
  'i-post': { viewBox: '0 0 24 24', body: "<path d=\"M12 21V5\"/><path d=\"M12 5h8l-2 3 2 3h-8\"/><path d=\"M8.5 21h7\"/>" },
  'i-recycle': { viewBox: '0 0 24 24', body: "<path d=\"M20 12a8 8 0 0 1-13.7 5.6\"/><path d=\"M4 12a8 8 0 0 1 13.7-5.6\"/><path d=\"M17.7 3v3.5h-3.5\"/><path d=\"M6.3 21v-3.5h3.5\"/>" },
  'i-route': { viewBox: '0 0 24 24', body: "<path d=\"M5 19c3.5 0 3.5-6 7-6s3.5-6 8-6\" stroke-dasharray=\"3 2.6\"/><circle cx=\"4.2\" cy=\"19\" r=\"1.6\"/><circle cx=\"20\" cy=\"7\" r=\"1.6\"/>" },
  'i-ruler': { viewBox: '0 0 24 24', body: "<rect x=\"2.5\" y=\"9\" width=\"19\" height=\"6\" rx=\"1.4\"/><path d=\"M7 9v2.6M11 9v3.4M15 9v2.6M19 9v3.4\"/>" },
  'i-scroll': { viewBox: '0 0 24 24', body: "<path d=\"M6 4.5h10a2 2 0 0 1 2 2v11a2.5 2.5 0 0 1-2.5 2.5H8a2 2 0 0 1-2-2V4.5Z\"/><path d=\"M6 4.5a2 2 0 0 0-2 2V8h2\"/><path d=\"M9.5 9.5h5M9.5 13.5h5\"/>" },
  'i-seagrass': { viewBox: '0 0 24 24', body: "<path d=\"M4 20.5h16\"/><path d=\"M8.5 20.5c0-4.8-1.4-7.6-3-9.6\"/><path d=\"M12 20.5V8\"/><path d=\"M15.5 20.5c0-4.8 1.4-7.6 3-9.6\"/>" },
  'i-shield': { viewBox: '0 0 24 24', body: "<path d=\"M12 3.5 5 6v6c0 4.2 3 7.1 7 8.5 4-1.4 7-4.3 7-8.5V6l-7-2.5Z\"/><path d=\"M8 12c1.3-1.3 2.7-1.3 4 0s2.7 1.3 4 0\"/>" },
  'i-station': { viewBox: '0 0 24 24', body: "<path d=\"M12 21v-7\"/><circle cx=\"12\" cy=\"11\" r=\"2.2\"/><path d=\"M7.8 6.8a6 6 0 0 0 0 8.4M16.2 6.8a6 6 0 0 1 0 8.4\"/><path d=\"M9 21h6\"/>" },
  'i-tree': { viewBox: '0 0 24 24', body: "<circle cx=\"12\" cy=\"9.2\" r=\"5.6\"/><path d=\"M12 14.8V21\"/><path d=\"M9 21h6\"/>" },
  'p-bandana': { viewBox: '0 0 48 48', body: "<path d=\"M7.5 13.5 L40.5 13.5 L24 38 Z\"/> <path d=\"M14 20 L34 20\"/> <path d=\"M18 26.5 L30 26.5\"/>" },
  'p-book': { viewBox: '0 0 48 48', body: "<path d=\"M11.5 9.5 L11.5 37.5 L24 34 L36.5 37.5 L36.5 9.5 L24 13 Z\"/> <path d=\"M24 13 L24 34\"/> <path d=\"M15.5 17.5 L20.5 16.2\"/> <path d=\"M27.5 16.2 L32.5 17.5\"/>" },
  'p-cap': { viewBox: '0 0 48 48', body: "<path d=\"M10 30 C10 19.5 16.3 12.5 24 12.5 C31.7 12.5 38 19.5 38 30\"/> <path d=\"M38 30 L42.5 30.5 C44 33 42 35 39 35 L10 35 C9 35 9 30 10 30 Z\"/> <path d=\"M24 12.5 L24 30\"/> <circle cx=\"24\" cy=\"11\" r=\"1.6\"/>" },
  'p-note': { viewBox: '0 0 48 48', body: "<path d=\"M16 8.5 L35 8.5 L35 39.5 L16 39.5 Z\"/> <path d=\"M13 13 A3 3 0 0 1 13 19\"/> <path d=\"M13 21 A3 3 0 0 1 13 27\"/> <path d=\"M13 29 A3 3 0 0 1 13 35\"/> <path d=\"M21 18 L30 18\"/> <path d=\"M21 24 L30 24\"/> <path d=\"M21 30 L27 30\"/>" },
  'p-pin': { viewBox: '0 0 48 48', body: "<circle cx=\"24\" cy=\"19\" r=\"10.5\"/> <circle cx=\"24\" cy=\"19\" r=\"4.5\"/> <path d=\"M24 29.5 L24 42\"/> <path d=\"M21 39.5 L27 39.5\"/>" },
  'p-poster': { viewBox: '0 0 48 48', body: "<path d=\"M12 7.5 L36 7.5 L36 36 C36 39.5 33.5 41 30.5 41 L12 41 Z\"/> <path d=\"M36 36 C36 38.2 33.8 39.5 31 39.5\"/> <path d=\"M17.5 15 L30.5 15\"/> <path d=\"M17.5 21 L30.5 21\"/> <path d=\"M17.5 27 L25.5 27\"/>" },
  'p-print': { viewBox: '0 0 48 48', body: "<rect x=\"9.5\" y=\"8.5\" width=\"29\" height=\"31\"/> <rect x=\"14.5\" y=\"13.5\" width=\"19\" height=\"21\"/> <path d=\"M15.5 31 L20.5 24.5 L24.5 28.5 L29 22 L32.5 27 L32.5 33.5 L15.5 33.5 Z\"/> <circle cx=\"19\" cy=\"18.5\" r=\"1.8\"/>" },
  'p-shirt': { viewBox: '0 0 48 48', body: "<path d=\"M17 7 L11.5 10.5 L8.5 20 L13.5 22 L15 18.5 L15 41 L33 41 L33 18.5 L34.5 22 L39.5 20 L36.5 10.5 L31 7\"/> <path d=\"M17 7 C18.5 11.5 21 13 24 13 C27 13 29.5 11.5 31 7\"/>" },
  'p-sticker': { viewBox: '0 0 48 48', body: "<rect x=\"8.5\" y=\"13.5\" width=\"19\" height=\"19\" rx=\"3\"/> <circle cx=\"31\" cy=\"27\" r=\"10.5\"/> <path d=\"M31 22.5 L31 31.5 M26.5 27 L35.5 27\"/>" },
  'p-tote': { viewBox: '0 0 48 48', body: "<path d=\"M12.5 16 L14.5 41 L33.5 41 L35.5 16 Z\"/> <path d=\"M19 16 C19 10 21 7.5 24 7.5 C27 7.5 29 10 29 16\"/> <path d=\"M18 24 L30 24\"/>" },
  'p-tumbler': { viewBox: '0 0 48 48', body: "<path d=\"M17.5 11 L30.5 11 L29.5 39 C29.5 40.7 28.4 41.5 27 41.5 L21 41.5 C19.6 41.5 18.5 40.7 18.5 39 Z\"/> <path d=\"M16 11 C16 8 18 6.5 24 6.5 C30 6.5 32 8 32 11\"/> <path d=\"M18 20.5 L30 20.5\"/> <path d=\"M18.3 27.5 L29.7 27.5\"/>" },
};
