/* GENERATED by scripts/extract-news.mjs — do not edit by hand. */
import img_mencari_sang_arsitek_hutan_papua_melalui_film_in_search_of_the_northern_cassowary from './mencari-sang-arsitek-hutan-papua-melalui-film-in-search-of-the-northern-cassowary.jpg';
import img_rekam_di_icrs_2026_membawa_neraca_sumber_daya_laut_indonesia_ke_panggung_global from './rekam-di-icrs-2026-membawa-neraca-sumber-daya-laut-indonesia-ke-panggung-global.jpg';
import img_the_last_place_on_earth_perjalanan_sembilan_tahun_yang_berbuah_penghargaan_internasional from './the-last-place-on-earth-perjalanan-sembilan-tahun-yang-berbuah-penghargaan-internasional.jpg';
import img_bangga_papua_hutan_papua_yang_dibangun_oleh_burung from './bangga-papua-hutan-papua-yang-dibangun-oleh-burung.jpg';
import img_rumah_baru_untuk_sains_dan_solusi_berbasis_alam_meresmikan_stasiun_riset_terpadu_jogo_laut from './rumah-baru-untuk-sains-dan-solusi-berbasis-alam-meresmikan-stasiun-riset-terpadu-jogo-laut.jpg';
import img_dari_perairan_lokal_ke_dialog_global_indonesia_di_sharks_international_2026 from './dari-perairan-lokal-ke-dialog-global-indonesia-di-sharks-international-2026.jpg';
import img_cerita_laut_dan_masa_depannya_mendorong_peran_generasi_muda_dalam_menjaga_masa_depan_laut_indonesia from './cerita-laut-dan-masa-depannya-mendorong-peran-generasi-muda-dalam-menjaga-masa-depan-laut-indonesia.jpg';
import img_multi_stakeholder_knowledge_management_based_on_co_production_principles_to_support_fisheries_resource_managament_in_indonesia from './multi-stakeholder-knowledge-management-based-on-co-production-principles-to-support-fisheries-resource-managament-in-indonesia.jpg';
import img_ketika_hutan_bercerita_film_manusia_dan_masa_depan_kehidupan from './ketika-hutan-bercerita-film-manusia-dan-masa-depan-kehidupan.jpg';
import img_mengintegrasikan_kualitas_habitat_ke_dalam_ukuran_keberlanjutan_cites from './mengintegrasikan-kualitas-habitat-ke-dalam-ukuran-keberlanjutan-cites.jpg';
import img_rekam_nusantara_di_cites_cop20 from './rekam-nusantara-di-cites-cop20.jpg';
import img_menjelajahi_peluang_dan_tantangan_pengelolaan_karbon_biru_di_indonesia from './menjelajahi-peluang-dan-tantangan-pengelolaan-karbon-biru-di-indonesia.jpg';
import img_konsultasi_nasional_bbnj_memperkuat_prioritas_nasional_indonesia_dalam_implementasi_perjanjian_bbnj from './konsultasi-nasional-bbnj-memperkuat-prioritas-nasional-indonesia-dalam-implementasi-perjanjian-bbnj.jpg';
import type { StaticImageData } from 'next/image';

export const COVERS: Record<string, StaticImageData> = {
  'berita/mencari-sang-arsitek-hutan-papua-melalui-film-in-search-of-the-northern-cassowary.jpg': img_mencari_sang_arsitek_hutan_papua_melalui_film_in_search_of_the_northern_cassowary,
  'berita/rekam-di-icrs-2026-membawa-neraca-sumber-daya-laut-indonesia-ke-panggung-global.jpg': img_rekam_di_icrs_2026_membawa_neraca_sumber_daya_laut_indonesia_ke_panggung_global,
  'berita/the-last-place-on-earth-perjalanan-sembilan-tahun-yang-berbuah-penghargaan-internasional.jpg': img_the_last_place_on_earth_perjalanan_sembilan_tahun_yang_berbuah_penghargaan_internasional,
  'berita/bangga-papua-hutan-papua-yang-dibangun-oleh-burung.jpg': img_bangga_papua_hutan_papua_yang_dibangun_oleh_burung,
  'berita/rumah-baru-untuk-sains-dan-solusi-berbasis-alam-meresmikan-stasiun-riset-terpadu-jogo-laut.jpg': img_rumah_baru_untuk_sains_dan_solusi_berbasis_alam_meresmikan_stasiun_riset_terpadu_jogo_laut,
  'berita/dari-perairan-lokal-ke-dialog-global-indonesia-di-sharks-international-2026.jpg': img_dari_perairan_lokal_ke_dialog_global_indonesia_di_sharks_international_2026,
  'berita/cerita-laut-dan-masa-depannya-mendorong-peran-generasi-muda-dalam-menjaga-masa-depan-laut-indonesia.jpg': img_cerita_laut_dan_masa_depannya_mendorong_peran_generasi_muda_dalam_menjaga_masa_depan_laut_indonesia,
  'berita/multi-stakeholder-knowledge-management-based-on-co-production-principles-to-support-fisheries-resource-managament-in-indonesia.jpg': img_multi_stakeholder_knowledge_management_based_on_co_production_principles_to_support_fisheries_resource_managament_in_indonesia,
  'berita/ketika-hutan-bercerita-film-manusia-dan-masa-depan-kehidupan.jpg': img_ketika_hutan_bercerita_film_manusia_dan_masa_depan_kehidupan,
  'berita/mengintegrasikan-kualitas-habitat-ke-dalam-ukuran-keberlanjutan-cites.jpg': img_mengintegrasikan_kualitas_habitat_ke_dalam_ukuran_keberlanjutan_cites,
  'berita/rekam-nusantara-di-cites-cop20.jpg': img_rekam_nusantara_di_cites_cop20,
  'berita/menjelajahi-peluang-dan-tantangan-pengelolaan-karbon-biru-di-indonesia.jpg': img_menjelajahi_peluang_dan_tantangan_pengelolaan_karbon_biru_di_indonesia,
  'berita/konsultasi-nasional-bbnj-memperkuat-prioritas-nasional-indonesia-dalam-implementasi-perjanjian-bbnj.jpg': img_konsultasi_nasional_bbnj_memperkuat_prioritas_nasional_indonesia_dalam_implementasi_perjanjian_bbnj,
};
