/* GENERATED by scripts/extract-about.mjs — do not edit by hand. */
import p_irfan_yulianto from './irfan-yulianto.jpg';
import p_yoki_hadiprakarsa from './yoki-hadiprakarsa.jpg';
import p_een_irawan_putra from './een-irawan-putra.jpg';
import p_nuraeni from './nuraeni.jpg';
import p_riki_rahmansyah from './riki-rahmansyah.jpg';
import p_efin_muttaqin from './efin-muttaqin.jpg';
import p_oktavianto_prastyo from './oktavianto-prastyo.jpg';
import p_dewi_pudiawati from './dewi-pudiawati.jpg';
import p_bernita_sumardja from './bernita-sumardja.jpg';
import p_aulia_nurahman from './aulia-nurahman.jpg';
import p_rizki_rukyanti from './rizki-rukyanti.jpg';
import p_masud_wijaya from './masud-wijaya.jpg';
import type { StaticImageData } from 'next/image';

export const PORTRAITS: Record<string, StaticImageData> = {
  'team/irfan-yulianto.jpg': p_irfan_yulianto,
  'team/yoki-hadiprakarsa.jpg': p_yoki_hadiprakarsa,
  'team/een-irawan-putra.jpg': p_een_irawan_putra,
  'team/nuraeni.jpg': p_nuraeni,
  'team/riki-rahmansyah.jpg': p_riki_rahmansyah,
  'team/efin-muttaqin.jpg': p_efin_muttaqin,
  'team/oktavianto-prastyo.jpg': p_oktavianto_prastyo,
  'team/dewi-pudiawati.jpg': p_dewi_pudiawati,
  'team/bernita-sumardja.jpg': p_bernita_sumardja,
  'team/aulia-nurahman.jpg': p_aulia_nurahman,
  'team/rizki-rukyanti.jpg': p_rizki_rukyanti,
  'team/masud-wijaya.jpg': p_masud_wijaya,
};
