/* One-off: lift every <symbol> out of the eleven static pages into one file
 * per icon under src/icons/.
 *
 * The old sprite was inlined per page, so #i-arrow was written out eleven
 * times and icons shared between the programme pages (i-map, i-people, i-board,
 * i-book, i-route, i-shield, i-bin) were retyped verbatim in each. This reports
 * any id whose definitions actually DIFFER between pages, because that would be
 * a real conflict rather than a duplicate — worth knowing before collapsing
 * them to a single source.
 *
 *   node scripts/extract-icons.mjs
 *
 * PROVENANCE. This reads site/, which was removed at cutover. To re-run it,
 * restore the original first:
 *
 *     git checkout baseline -- site/
 *
 * The tag `baseline` is the untouched static site as imported.
 */

import fs from 'node:fs';
import path from 'node:path';

const SITE = 'site';
const OUT = 'src/icons';

const norm = (s) => s.replace(/\s+/g, ' ').trim();

/** id -> { viewBox, body, pages: [] } */
const icons = new Map();
const conflicts = [];

for (const file of fs.readdirSync(SITE).filter((f) => f.endsWith('.html')).sort()) {
  const html = fs.readFileSync(path.join(SITE, file), 'utf8');
  for (const m of html.matchAll(/<symbol\s+id="([^"]+)"\s+viewBox="([^"]+)"\s*>([\s\S]*?)<\/symbol>/g)) {
    const [, id, viewBox, body] = m;
    const entry = { viewBox: norm(viewBox), body: norm(body) };
    const seen = icons.get(id);
    if (!seen) {
      icons.set(id, { ...entry, pages: [file] });
    } else {
      seen.pages.push(file);
      if (seen.viewBox !== entry.viewBox || seen.body !== entry.body) {
        conflicts.push({ id, first: seen.pages[0], other: file });
      }
    }
  }
}

fs.mkdirSync(OUT, { recursive: true });
for (const [id, { viewBox, body }] of icons) {
  fs.writeFileSync(path.join(OUT, `${id}.svg`), `<svg viewBox="${viewBox}">${body}</svg>\n`);
}

/* Also emit a typed module. The .svg files stay the readable, diffable source
   of truth, but Next runs on Turbopack, where Vite's import.meta.glob does not
   exist — and reading from src/ with fs at runtime is fragile. Generating a
   plain import keeps the sprite working in every rendering mode, and the union
   type turns a typo'd icon id into a compile error instead of a blank space. */
const sorted = [...icons.entries()].sort(([a], [b]) => a.localeCompare(b));
const entries = sorted
  .map(([id, { viewBox, body }]) => `  '${id}': { viewBox: '${viewBox}', body: ${JSON.stringify(body)} },`)
  .join('\n');

fs.writeFileSync(
  path.join(OUT, 'index.ts'),
  `/* GENERATED by scripts/extract-icons.mjs — do not edit by hand.
 * Source of truth is the .svg files beside this one; rerun the script after
 * changing them. ${icons.size} icons, lifted out of the inline sprites that the
 * old pages each carried a copy of.
 */

export type IconId =
${sorted.map(([id]) => `  | '${id}'`).join('\n')};

export const ICONS: Record<IconId, { viewBox: string; body: string }> = {
${entries}
};
`
);

const shared = [...icons.entries()].filter(([, v]) => v.pages.length > 1);
console.log(`${icons.size} ikon unik ditulis ke ${OUT}/`);
console.log(`${shared.length} di antaranya sebelumnya diduplikasi di beberapa halaman:`);
for (const [id, v] of shared.sort((a, b) => b[1].pages.length - a[1].pages.length)) {
  console.log(`  ${id.padEnd(14)} ${v.pages.length}x  ${v.pages.join(', ')}`);
}
console.log(conflicts.length ? `\nKONFLIK (definisi berbeda untuk id sama):` : `\nTidak ada konflik — semua duplikat identik.`);
for (const c of conflicts) console.log(`  ${c.id}: ${c.first} vs ${c.other}`);
