/* GENERATED by scripts/extract-about.mjs — do not edit by hand. */
import u_0 from './frci.png';
import u_1 from './infis.png';
import u_2 from './urban.png';
import type { StaticImageData } from 'next/image';

export const UNIT_LOGOS: Record<string, StaticImageData> = {
  'unit/frci.png': u_0,
  'unit/infis.png': u_1,
  'unit/urban.png': u_2,
};
